config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  root 'welcome#index'

  resources :recipes do
    resources :ingredients
    resources :directions
  end

  resources :users, only: [:new, :create]

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end
  
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base

  validates :title, presence: true,
                    length: { minimum: 3 }
  validates :description, presence: true

  belongs_to :user
  belongs_to :category

  has_many :directions, dependent: :destroy
  has_many :ingredients, dependent: :destroy

  mount_uploader :image, ImageUploader

  def update_recipe_ingredients
    ActiveRecord::Base.transaction do
      set_zeros
      conversion
      calc_weight
      calc_it
      save ? self : false
    end
  end

  def build_recipe(recipe_params)
    # this adds all the transactions in one commit.
    ActiveRecord::Base.transaction do
      save_or_update(recipe_params)
      set_zeros
      calc_weight
      calc_it
      save ? self : false
    end
  end

  def save_or_update(data)
    persisted? ? update(data) : save
  end

  private

  def conversion
    ingredient = ingredients.last
    if ingredient.unit == "oz"
      ingredient.update!(qty: ingredient.qty * 28.35, unit: "g")
    elsif ingredient.unit == "lb"
      ingredient.update!(qty: ingredient.qty * 453.59, unit: "g")
    elsif ingredient.unit == "kg"
      ingredient.update!(qty: ingredient.qty * 1000, unit: "g")
    end
  end

  def calc_it
    self.calories = calc_calorie
    self.total_fat = calc_total_fat
    self.saturated_fat = calc_sat_fat
    self.trans_fat = calc_trans_fat
    self.cholesterol = calc_cholesterol
    self.sodium = calc_sodium
    self.total_carbs = calc_total_carbs
    self.dietary_fiber = calc_dietary_fiber
    self.sugars = calc_sugars
    self.protein = calc_protein
    self.vitamin_a = calc_vitamin_a
    self.vitamin_c = calc_vitamin_c
    self.calcium = calc_calcium
    self.iron = calc_iron
  end

  def calc_weight
    self.total_weight = self.ingredients.sum(:qty)
  end
  # this calculates the values correctly...
  def calc_calorie
    self.ingredients.map {|x| x.calories * x.qty }.sum
  end

  def calc_total_fat
    self.ingredients.map {|x| x.total_fat * x.qty }.sum
  end

  def calc_sat_fat
    self.ingredients.map {|x| x.saturated_fat * x.qty }.sum
  end

  def calc_trans_fat
    self.ingredients.map {|x| x.trans_fat * x.qty }.sum
  end

  def calc_cholesterol
    self.ingredients.map {|x| x.cholesterol * x.qty }.sum * 1000
  end

  def calc_sodium
    self.ingredients.map {|x| x.sodium * x.qty }.sum * 1000
  end

  def calc_total_carbs
    self.ingredients.map {|x| x.total_carbs * x.qty }.sum
  end

  def calc_dietary_fiber
    self.ingredients.map {|x| x.dietary_fiber * x.qty }.sum
  end

  def calc_sugars
    self.ingredients.map {|x| x.sugars * x.qty }.sum
  end

  def calc_protein
    self.ingredients.map {|x| x.protein * x.qty }.sum
  end

  def calc_vitamin_a
    self.ingredients.map {|x| x.vitamin_a * x.qty }.sum
  end

  def calc_vitamin_c
    self.ingredients.map {|x| x.vitamin_c * x.qty }.sum
  end

  def calc_calcium
    self.ingredients.map {|x| x.calcium * x.qty }.sum
  end

  def calc_iron
    self.ingredients.map {|x| x.iron * x.qty }.sum
  end

  def set_zeros
    self.calories ||= 0
    self.total_fat ||= 0
    self.saturated_fat ||= 0
    self.trans_fat ||= 0
    self.cholesterol ||= 0
    self.sodium ||= 0
    self.total_carbs ||= 0
    self.dietary_fiber ||= 0
    self.sugars ||= 0
    self.protein ||= 0
    self.vitamin_a ||= 0
    self.vitamin_c ||= 0
    self.calcium ||= 0
    self.iron ||= 0
    self.servings ||= 1
  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  before_action :authenticate_user!, only: [:create, :new, :edit, :update, :destroy]
  before_action :find_recipe, only: [:show, :edit, :update, :destroy]


  def index
    @appetizers = Category.category_search(Category::APPETIZER)
    @entrees = Category.category_search(Category::ENTREE)
    @desserts = Category.category_search(Category::DESSERT)
    @sides = Category.category_search(Category::SIDES)
    @bulk_recipes = Category.category_search(Category::BULK_RECIPES)
    @inactive = Category.category_search(Category::INACTIVE)
    @recipe = Recipe.new
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = current_user.recipes.new recipe_params
    if @recipe.build_recipe(recipe_params)
      redirect_to recipe_path(@recipe)
    else
      render :new
    end
  end

  def show
    @ingredient = Ingredient.new
    @direction = Direction.new
  end

  def edit
  end

  def update
    respond_to do |format|
      if @recipe.build_recipe(recipe_params)
        format.html { redirect_to recipe_path(@recipe), notice: "Recipe Successfully updated" }
        format.json { respond_with_bip(@recipe) }
      else
        format.html { flash[:notice] = "Could not update" }
      end
    end
  end

  def destroy
    @recipe.destroy
    redirect_to recipes_path, notice: "Successfully Deleted"
  end

  private

  def find_recipe
    @recipe = Recipe.find params[:id]
  end

  def recipe_params
    params.require(:recipe).permit(:title, :description, :image, :price, :servings, :category_id, { ingredients_attributes: ingredient_params }, { directions_attributes: directions_params } )
  end

  def ingredient_params
    [:id, :qty, :unit, :name, :calories, :total_fat, :saturated_fat, :trans_fat, :cholesterol, :sodium, :total_carbs, :dietary_fiber, :sugars, :protein, :vitamin_a, :vitamin_c, :calcium, :iron, :nutrient_databank_number, :serving_weight, :nutritionix_id, :_destroy]
  end

  def directions_params
    [:id, :step, :instruction, :_destroy]
  end

end

app/helpers/recipes_helper.rb
module RecipesHelper

  def weight_per_serving
    (@recipe.total_weight / @recipe.servings).round(1)
  end

  def calories_per_serving
    (@recipe.calories / @recipe.servings).round(0)
  end

  def calories_from_fat_per_serving
    calorie_multiplier = 9
    ((@recipe.total_fat * calorie_multiplier)/@recipe.servings).round(0)
  end

  def total_fat_per_serving
    (@recipe.total_fat/@recipe.servings).round(0)
  end

  def dv_total_fat_per_serving
    max_total_fat = 65
    ((@recipe.total_fat / max_total_fat * 100)/@recipe.servings).round(0)
  end

  def sat_fat_per_serving
    (@recipe.saturated_fat/@recipe.servings).round(0)
  end

  def dv_sat_fat_per_serving
    max_sat_fat = 20
    ((@recipe.saturated_fat / max_sat_fat * 100)/@recipe.servings).round(0)
  end

  def trans_fat_per_serving
    (@recipe.trans_fat/@recipe.servings).round(0)
  end

  def cholesterol_per_serving
    (@recipe.cholesterol/@recipe.servings).round(0)
  end

  def dv_cholesterol_per_serving
    max_cholesterol = 300
    ((@recipe.cholesterol / max_cholesterol * 100)/@recipe.servings).round(0)
  end

  def sodium_per_serving
    (@recipe.sodium/@recipe.servings).round(0)
  end

  def dv_sodium_per_serving
    max_sodium = 2400
    ((@recipe.sodium / max_sodium * 100)/@recipe.servings).round(0)
  end

  def carbs_per_serving
    (@recipe.total_carbs/@recipe.servings).round(0)
  end

  def dv_carbs_per_serving
    max_carbs = 300
    ((@recipe.total_carbs / max_carbs * 100)/@recipe.servings).round(0)
  end

  def dietary_fiber_per_serving
    (@recipe.dietary_fiber/@recipe.servings).round(0)
  end

  def dv_dietary_fiber_per_serving
    max_dietary_fiber = 25
    (@recipe.dietary_fiber / max_dietary_fiber * 100).round(0)
  end

  def sugar_per_serving
    (@recipe.sugars/@recipe.servings).round(0)
  end

  def protein_per_serving
    (@recipe.protein/@recipe.servings).round(0)
  end

  def dv_vitamin_a_per_serving
    (@recipe.vitamin_a/@recipe.servings).round(0)
  end

  def dv_vitamin_c_per_serving
    (@recipe.vitamin_c/@recipe.servings).round(0)
  end

  def dv_calcium_per_serving
    (@recipe.calcium/@recipe.servings).round(0)
  end

  def dv_iron_per_serving
    (@recipe.iron/@recipe.servings).round(0)
  end

  def fat_content_description(dv_fat_content)
    if dv_fat_content > 25
      "Very High Fat Content"
    elsif dv_fat_content > 15
      "High Fat Content"
    elsif dv_fat_content > 10
      "Average Fat Content"
    elsif dv_fat_content > 5
      "Low Fat Content"
    elsif dv_fat_content > 0
      "Very Low Fat Content"
    else dv_fat_content == 0
      "No Fat Content"
    end
  end

  def cholesterol_content_description(dv_cholesterol_content)
    if dv_cholesterol_content > 25
      "Very High Cholesterol Content"
    elsif dv_cholesterol_content > 15
      "High Cholesterol Content"
    elsif dv_cholesterol_content > 10
      "Average Cholesterol Content"
    elsif dv_cholesterol_content > 5
      "Low Cholesterol Content"
    elsif dv_cholesterol_content > 0
      "Very Low Cholesterol Content"
    else dv_cholesterol_content == 0
      "No Cholesterol"
    end
  end

  def sodium_content_description(dv_sodium_content)
    if dv_sodium_content > 25
      "Very High Sodium Content"
    elsif dv_sodium_content > 15
      "High Sodium Content"
    elsif dv_sodium_content > 10
      "Average Sodium Content"
    elsif dv_sodium_content > 5
      "Low Sodium Content"
    elsif dv_sodium_content > 0
      "Very Low Sodium Content"
    else dv_sodium_content == 0
      "No Sodium"
    end
  end

  def total_carbs_content_description(dv_carb_content)
    if dv_carb_content > 25
      "Very High Carbohydrates Content"
    elsif dv_carb_content > 15
      "High Carbohydrates Content"
    elsif dv_carb_content > 10
      "Average Carbohydrates Content"
    elsif dv_carb_content > 5
      "Low Carbohydrates Content"
    elsif dv_carb_content > 0
      "Very Low Carbohydrates Content"
    else dv_carb_content == 0
      "No Carbohydrates"
    end
  end

end

app/views/recipes/_direction_fields.html.erb
<%= simple_form_for [@recipe, @direction] do |f| %>
  <%= f.input :instruction, label: false, placeholder: "add directions here...", input_html: { class: 'form-input form-control' } %>
  <%= f.submit "Add Step", class: "btn btn-primary" %>
<% end %>

app/views/recipes/_ingredient_fields.html.erb
<%= simple_form_for [@recipe, @ingredient], html: {class: "form-inline form-horizontal"} do |f| %>
<div class="ingredient">
    <div class="col-xs-2">
      <%= f.input :qty, label: false, placeholder: "qty", input_html: { class: 'form-input form-control qty-input'} %>
    </div>
    <div class="col-xs-2">
      <%= f.input :unit, label: false, placeholder: "g", input_html: { class: 'form-input form-control unit-input' } %>
    </div>
    <div class="col-xs-5">
      <%= f.input :name, label: false, placeholder: "Search Ingredients", input_html: { class: 'form-input form-control search-term search-items', id: 'search-items' } %>
    </div>


  <%= f.input :calories, input_html: { class: 'form-input form-control calories-field' }, as: :string, as: :hidden %>
  <%= f.input :total_fat, input_html: { class: 'form-input form-control total-fat-field' }, as: :string, as: :hidden %>
  <%= f.input :saturated_fat, input_html: { class: 'form-input form-control saturated-fat-field' }, as: :string, as: :hidden %>
  <%= f.input :trans_fat, input_html: { class: 'form-input form-control trans-fat-field' }, as: :string, as: :hidden %>
  <%= f.input :cholesterol, input_html: { class: 'form-input form-control cholesterol-field' }, as: :string, as: :hidden %>
  <%= f.input :sodium, input_html: { class: 'form-input form-control sodium-field' }, as: :string, as: :hidden %>
  <%= f.input :total_carbs, input_html: { class: 'form-input form-control total-carbs-field' }, as: :string, as: :hidden %>
  <%= f.input :dietary_fiber, input_html: { class: 'form-input form-control dietary-fiber-field' }, as: :string, as: :hidden %>
  <%= f.input :sugars, input_html: { class: 'form-input form-control sugars-field' }, as: :string, as: :hidden %>
  <%= f.input :protein, input_html: { class: 'form-input form-control protein-field' }, as: :string, as: :hidden %>
  <%= f.input :vitamin_a, input_html: { class: 'form-input form-control vitamin-a-field' }, as: :string, as: :hidden %>
  <%= f.input :vitamin_c, input_html: { class: 'form-input form-control vitamin-c-field' }, as: :string, as: :hidden %>
  <%= f.input :calcium, input_html: { class: 'form-input form-control calcium-field' }, as: :string, as: :hidden %>
  <%= f.input :iron, input_html: { class: 'form-input form-control iron-field' }, as: :string, as: :hidden %>
  <%= f.input :nutritionix_id, input_html: { class: 'form-input form-control ingredient-id-field' }, as: :string, as: :hidden %>
  <%= f.input :serving_weight, input_html: { class: 'form-input form-control serving-weight-field' }, as: :string, as: :hidden %>
  <div class="col-xs-3">
    <%= f.submit "Add", class: "btn btn-primary"  %>
  </div>
</div>
<% end %>

app/views/recipes/_list_recipes.html.erb
<div class="each-recipe">
  <div class="col-xs-1">
    <% if can? :edit, r %>
      <%= link_to '<i class="fa fa-pencil"></i>'.html_safe, edit_recipe_path(r) %>
    <% end %>
    <% if can? :destroy, r %>
      <%= link_to '<i class="fa fa-trash x4"></i>'.html_safe, recipe_path(r), method: :delete, data: { confirm: "are you sure?"} %>
    <% end %>
  </div>
  <div class="col-xs-11">
  <div class="title">
    <h2 class="recipe-title"><%= link_to r.title, recipe_path(r) %></h2>
  </div>
  <% if (r.price != nil) %>
  <h2>|</h2><span><h2><%= r.price.to_i %></h2></span>
    <% end %>
  <p><%= link_to r.description %></p>
  </div>
</div>

app/views/recipes/_new_recipe.html.erb
<div class="container">
  <div class="col-xs-6">
    <div class="modal-body">
      <%= simple_form_for (@recipe || Recipe.new), html: {class: "form-horizontal"} do |f| %>
        <%= f.input :title, placeholder: "Add recipe title", class: "form-control title-form" %>
        <%= f.input :description, placeholder: "Write a recipe description", class: "form-control description-form" %>
        <%= f.input :image, class: "form-control" %>
        <%= f.input :servings, label: "Servings per recipe", input_html: { class: 'form-input form-control unit-input', :style=> 'width: 60px; padding: 5px; text-align: center', min: "1" , value: 1 } %>
        <%= f.input :price, placeholder: "$$$", as: :decimal, input_html: { class: 'form-input form-control unit-input', :style=> 'width: 60px; padding: 5px; text-align: center' } %>
        <%= f.association :category, as: :select, collection: Category.order(:created_at) %>
        <div class="loading-graphic"></div>
    </div>
    <div class="modal-footer">
      <%= f.submit class: "btn btn-primary recipe-save-btn" %>
      <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    </div>
      <% end %>
  </div>
</div>

app/views/recipes/_nutrition_recommendation.html.erb
<h2>Nutritional Analysis</h2>

<h4>Fat Content</h4>
<% if ( dv_total_fat_per_serving > 25) %>
  <p class="bad-nut"><%= fat_content_description(dv_total_fat_per_serving) %></p>
<% elsif (dv_total_fat_per_serving > 15) %>
  <p class="avg-nut"><%= fat_content_description(dv_total_fat_per_serving) %></p>
<% else %>
  <p class="good-nut"><%= fat_content_description(dv_total_fat_per_serving) %></p>
<% end %>
<div class="progress">
  <div class="progress-bar progress-bar-striped active" role="progressbar"
  aria-valuenow="10" aria-valuemin="0" aria-valuemax="100" style="width:<%= dv_total_fat_per_serving %>%">
  DV <%= dv_total_fat_per_serving %> %
  </div>
</div>

<h4>Cholesterol Content</h4>
<% if ( dv_cholesterol_per_serving > 25) %>
  <p class="bad-nut"><%= cholesterol_content_description(dv_cholesterol_per_serving) %></p>
<% elsif (dv_cholesterol_per_serving > 15) %>
  <p class="avg-nut"><%= cholesterol_content_description(dv_cholesterol_per_serving) %></p>
<% else %>
  <p class="good-nut"><%= cholesterol_content_description(dv_cholesterol_per_serving) %></p>
<% end %>
<div class="progress">
  <div class="progress-bar progress-bar-striped active" role="progressbar"
  aria-valuenow="10" aria-valuemin="0" aria-valuemax="100" style="width:<%= dv_cholesterol_per_serving %>%">
  DV <%= dv_cholesterol_per_serving %> %
  </div>
</div>

<h4>Sodium Content</h4>
<% if (dv_sodium_per_serving > 25) %>
  <p class="bad-nut"><%= sodium_content_description(dv_sodium_per_serving) %></p>
<% elsif (dv_sodium_per_serving > 15) %>
  <p class="avg-nut"><%= sodium_content_description(dv_sodium_per_serving) %></p>
<% else %>
  <p class="good-nut"><%= sodium_content_description(dv_sodium_per_serving) %></p>
<% end %>
<div class="progress">
  <div class="progress-bar progress-bar-striped active" role="progressbar"
  aria-valuenow="10" aria-valuemin="0" aria-valuemax="100" style="width:<%= dv_sodium_per_serving %>%">
  DV <%= dv_sodium_per_serving %> %
  </div>
</div>

<h4>Total Carbohydrates Content</h4>
<% if (dv_carbs_per_serving > 25) %>
  <p class="bad-nut"><%= total_carbs_content_description(dv_carbs_per_serving) %></p>
<% elsif (dv_carbs_per_serving > 15) %>
  <p class="avg-nut"><%= total_carbs_content_description(dv_carbs_per_serving) %></p>
<% else %>
  <p class="good-nut"><%= total_carbs_content_description(dv_carbs_per_serving) %></p>
<% end %>
<div class="progress">
  <div class="progress-bar progress-bar-striped active" role="progressbar"
  aria-valuenow="10" aria-valuemin="0" aria-valuemax="100" style="width:<%= dv_carbs_per_serving %>%">
  DV <%= dv_carbs_per_serving %> %
  </div>
</div>

<div class="recommendations-footnote">
  <p>**Percentage of daily values</p>
  <div class="col-xs-6">
    <p>> 25% - Very High</p>
    <p>15% - 25% High</p>
  </div>
  <div class="col-xs-6">
    <p>10% - 15% - Average</p>
    <p>5% - 10% - Low</p>
  </div>
</div>

app/views/recipes/_nutritional_table.html.erb
<div class="nutritional-table">
  <div class="title">Nutrition Facts</div>
  <div class="recipe-name"><%= @recipe.title %></div>

  <div class="serving-size">
    Serving Size: <%= weight_per_serving %> g
  </div>
  <div class="no-servings">
    Servings: <input type="number" name="quantity" min="1" class="no-val" value="1"></input>
  </div>
  <div class="thick-bar"></div>
  <div class="amount-per-serving">
    Totals
  </div>
  <div class="thin-bar"></div>
  <div class="calories">
    <div class="c-bold">
      Calories
      <span class="c-thin calories-no">
        <%= calories_per_serving %>
      </span>
    </div>
    <div class="c-fat">
      Calories from Fat
      <span class="c-fat-thin calories-fat-no">
        <%= calories_from_fat_per_serving %>
      </span>
    </div>
  </div>
  <div class="medium-bar"></div>
  <div class="percent-dv">% Daily Value*</div>
  <div class="thin-bar"></div>
  <div class="fat">
    <div class="total_fat">
      <b>Total Fat </b>
      <span class="total-fat-no">
        <%= total_fat_per_serving %>
      </span>
       g
       <span class="dv-percent">
         <span class="dv-total-fat">
           <%= dv_total_fat_per_serving %>
         </span> %
       </span>
     </div>
    <div class="thin-bar-short"></div>
    <div class="sat-fat minor">
      Saturated Fat
      <span class="sat-fat-no">
        <%= sat_fat_per_serving %>
      </span> g
      <span class="dv-percent">
        <span class="dv-sat-fat">
          <%= dv_sat_fat_per_serving %>
        </span> %
      </span>
    </div>
    <div class="thin-bar-short"></div>
    <div class="sat-fat minor">
      <span class="trans">Trans</span>
       Fat
      <span class="trans-fat-no">
        <%= @recipe.trans_fat.present? ? trans_fat_per_serving : 0 %>
      </span> g
    </div>
  </div>
  <div class="thin-bar"></div>
  <div class="cholesterol">
    <b>Cholesterol</b>
    <span class="cholesterol-no">
      <%= cholesterol_per_serving %>
    </span> mg
    <span class="dv-percent">
      <span class="dv-cholesterol">
        <%= dv_cholesterol_per_serving %>
      </span> %
    </span>
  </div>
  <div class="thin-bar"></div>
  <div class="protein">
    <b>Sodium</b>
    <span class="sodium-no">
      <%= sodium_per_serving %>
    </span> mg
    <span class="dv-percent">
      <span class="dv-sodium">
        <%= dv_sodium_per_serving %>
      </span> %
    </span>
  </div>
  <div class="thin-bar"></div>
  <div class="carbs">
    <b>Total Carbohydrates </b>
    <span class="total-carbs-no">
      <%= carbs_per_serving %>
    </span> g
    <span class="dv-percent">
      <span class="dv-total-carbs">
        <%= dv_carbs_per_serving %>
      </span> %
    </span>
    <div class="thin-bar-short"></div>
    <div class="fiber minor">Dietary Fiber
      <span class="fiber-no">
        <%= dietary_fiber_per_serving %>
      </span> g
      <span class="dv-percent">
        <span class="dv-fiber">
          <%= dv_dietary_fiber_per_serving %>
        </span> %
      </span>
    </div>
    <div class="thin-bar-short"></div>
    <div class="sugars minor">Sugars
      <span class="sugar-no">
        <%= sugar_per_serving %>
      </span> g
    </div>
  </div>
  <div class="thin-bar"></div>
  <div class="protein">
    <b>Protein </b>
    <span class="protein-no">
      <%= protein_per_serving %>
    </span> g
  </div>
  <div class="thick-bar"></div>
  <div class="dv">
    Vitamin A
    <span class="dv-percent">
      <span class="vit-a-no">
        <%= dv_vitamin_a_per_serving %>
      </span> %
    </span>
  </div>
  <div class="thin-bar"></div>
  <div class="dv">
    Vitamin C
    <span class="dv-percent">
      <span class="vit-c-no">
        <%= dv_vitamin_c_per_serving %>
      </span> %
    </span>
  </div>
  <div class="thin-bar"></div>
  <div class="dv">
    Calcium
    <span class="dv-percent">
      <span class="calcium-no">
        <%= dv_calcium_per_serving %>
      </span> %
    </span>
  </div>
  <div class="thin-bar"></div>
  <div class="dv">
    Iron
    <span class="dv-percent">
      <span class="iron-no">
        <%= dv_iron_per_serving %>
      </span> %
    </span>
  </div>
  <div class="thin-bar"></div>
  <div class="nutrition-comment">* Percent daily values are based on a 2000 calorie diet</div>
</div>

app/views/recipes/index.html.erb
<div class="container">
  <% if current_user %>
  <div class="col-xs-6">
    <h1><%= current_user.rest_name %></h1>
  </div>
  <% end %>
  <div class="col-xs-6">
    <input style="width: 300px" type="text" id="filter-library" class="form-control filter-form" placeholder="Filter..."/>
  </div>
  <div class="list-all-line"></div>
  <%= render '/recipes/show_recipes' %>
</div>

app/views/recipes/show.html.erb
<div class="container">
  <div class="container">
    <div class="col-md-4 recipe-image">
      <%= link_to "Back", recipes_path, class: "btn btn-default" %>
      <% if can? :destroy, @recipe %>
        <%= link_to '<i class="fa fa-trash x4"></i>'.html_safe, recipe_path(@recipe), method: :delete, data: { confirm: "are you sure?"}, class: "show-icon" %>
      <% end %>
      <% if can? :edit, @recipe %>
        <%= link_to '<i class="fa fa-pencil x4"></i>'.html_safe, edit_recipe_path(@recipe), class: "show-icon" %>
      <% end %>
      <% if @recipe.image.url(:large).nil? %>
        <h3>No Image Provided</h3>
      <% else %>
        <%= image_tag @recipe.image.url(:large), class: "img-responsive img-recipe" %>
      <% end %>
      <div class="recipe-category">
        <%= @recipe.category.name %>
      </div>
      <% if can? :edit, @recipe %>
        <div data-toggle="tooltip" data-placement="bottom" title="Edit the title...">
          <h1><%= best_in_place @recipe, :title, as: :input, :html_attrs => { :style => 'width:100%;' } %></h1>
        </div>
      <% else %>
        <h1><%= @recipe.title %></h1>
      <% end %>

      <% if can? :edit, @recipe %>
        <p data-toggle="tooltip" data-placement="bottom" title="Edit the description..."><%= best_in_place @recipe, :description, as: :input, :html_attrs => { :style => 'width:100%;' } %></p>
      <% else %>
        <p><%= @recipe.description %></p>
      <% end %>
      <br>
    </div>
    <div class="col-md-4 nut-recommendation">
      <%= render 'nutrition_recommendation' %>
    </div>
    <div class="col-md-4 nut-table">
      <%= render 'nutritional_table' %>
    </div>
  </div>
  <% if can? :edit, @recipe %>
  <div class="container ingredient-directions">
      <div class="col-xs-12">
        <div class="col-xs-4 servings-number">
          <p data-toggle="tooltip" data-placement="bottom" title="Number of servings per recipe...">Servings per recipe: <%= best_in_place @recipe, :servings, as: :input, :html_attrs => { :style => 'width:100%;' } %></p>
        </div>
      </div>
    <div class="col-md-6 ingredients">
      <h2>Ingredients</h2>
      <table class="table table-striped table-hover">
        <tbody class="each-ingredient">
        <tr>
          <th>Qty</th>
          <th>Unit</th>
          <th>Ingredient</th>
          <% if can? :destroy, @recipe %>
            <th>Delete</th>
          <% end %>
        </tr>
          <% @recipe.ingredients.each do |ingredient| %>
            <%= render partial: 'ingredients/ingredients', locals: { ingredient: ingredient } %>
          <% end %>
        </tbody>
      </table>
      <div class="ingredient-form">
      <% if can? :edit, @recipe %>
        <%= render '/ingredients/ingredient_fields' %>
      <% end %>
      </div>
    </div>

    <div class="col-md-6 directions">
      <h2>Directions</h2>
      <div class="direction-underline"></div>
      <div class="inner-directions">
          <ol>
            <div class="each-direction">
              <% @recipe.directions.order(:created_at).each do |direction| %>
                <%= render partial: 'directions/directions', locals: { direction: direction } %>
              <% end %>
            </div>
          </ol>
        <div class="col-md-10">
          <div class="direction_form">
            <% if can? :edit, @recipe %>
              <%= render 'directions/direction_fields' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>