config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  root 'welcome#index'

  resources :recipes do
    resources :ingredients
    resources :directions
  end

  resources :users, only: [:new, :create]

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end
  
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  belongs_to :recipe

  validates :qty, presence: true, numericality: { greater_than: 0 }
  validates :name, presence: true
  validates :calories, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :total_fat, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :saturated_fat, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :cholesterol, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :sodium, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :total_carbs, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :dietary_fiber, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :sugars, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :protein, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :vitamin_a, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :vitamin_c, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :calcium, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :iron, presence: true, numericality: { greater_than_or_equal_to: 0 }

  after_create :set_zeros

  def set_zeros
    self.calories ||= 0
    self.total_fat ||= 0
    self.saturated_fat ||= 0
    self.trans_fat ||= 0
    self.cholesterol ||= 0
    self.sodium ||= 0
    self.total_carbs ||= 0
    self.dietary_fiber ||= 0
    self.sugars ||= 0
    self.protein ||= 0
    self.vitamin_a ||= 0
    self.vitamin_c ||= 0
    self.calcium ||= 0
    self.iron ||= 0
  end

end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController

  before_action :authenticate_user!

  def create
    @recipe = Recipe.find params[:recipe_id]
    @ingredient = @recipe.ingredients.new ingredient_params

    respond_to do |format|
      if @ingredient.save
        @recipe.update_recipe_ingredients
        format.html { redirect_to recipe_path(@recipe) }
        format.js { render }
      else
        format.html { render "recipe/show" }
        format.js { render }
      end
    end

  end

  def destroy
    @recipe = Recipe.find params[:recipe_id]
    @ingredient = Ingredient.find params[:id]
    @ingredient.destroy
    @recipe.update_recipe_ingredients
    respond_to do |format|
      format.html { redirect_to recipe_path(@recipe), notice: "Successfully Deleted" }
      format.js { render }
    end
  end

  private

  def ingredient_params
    params.require(:ingredient).permit(:id, :qty, :unit, :name, :calories, :total_fat, :saturated_fat, :trans_fat, :cholesterol, :sodium, :total_carbs, :dietary_fiber, :sugars, :protein, :vitamin_a, :vitamin_c, :calcium, :iron, :nutrient_databank_number, :serving_weight, :nutritionix_id)
  end

end

app/views/ingredients/_ingredient.html.erb
<div id="<%= dom_id(i) %>">
  <tr>
    <td><p><%= i.qty %></p></td>
    <td><p><%= i.unit %></p></td>
    <td><p><%= i.name %></p></td>
    <!-- <td><%#= link_to '<i class="fa fa-pencil x4"></i>'.html_safe, edit_recipe_ingredient_path(@recipe, i) %></td> -->
    <td><%= link_to '<i class="fa fa-trash x3"></i>'.html_safe, recipe_ingredient_path(@recipe, i), method: :delete, data: { confirm: "are you sure?"}, remote: true %></td>
  <tr>
</div>

app/views/ingredients/_ingredient_fields.html.erb
<%= simple_form_for [@recipe, @ingredient], remote: true, html: {class: "form-inline form-horizontal"} do |f| %>
<div class="ingredient">
  <div class="col-xs-2">
    <%= f.input :qty, label: false, placeholder: "qty", input_html: { class: 'form-input form-control qty-input', :style=> 'width: 55px; padding: 3px; text-align: center'} %>
  </div>
  <div class="col-xs-2">
    <%= f.input :unit, collection: ["g", "kg", "oz", "lb"], label: false, placeholder: "g", input_html: { class: 'form-input form-control unit-input', :style=> 'width: 50px; padding: 5px; text-align: center' } %>
  </div>
  <div class="col-xs-5">
    <%= f.input :name, label: false, placeholder: "Search Ingredients", input_html: { class: 'form-input form-control search-term search-items', id: 'search-items', :style=> 'width: 190px; padding: 5px', autocomplete: "off"  } %>
  </div>

  <%= f.input :calories, input_html: { class: 'form-input form-control calories-field' }, as: :string, as: :hidden %>
  <%= f.input :total_fat, input_html: { class: 'form-input form-control total-fat-field' }, as: :string, as: :hidden %>
  <%= f.input :saturated_fat, input_html: { class: 'form-input form-control saturated-fat-field' }, as: :string, as: :hidden %>
  <%= f.input :trans_fat, input_html: { class: 'form-input form-control trans-fat-field' }, as: :string, as: :hidden %>
  <%= f.input :cholesterol, input_html: { class: 'form-input form-control cholesterol-field' }, as: :string, as: :hidden %>
  <%= f.input :sodium, input_html: { class: 'form-input form-control sodium-field' }, as: :string, as: :hidden %>
  <%= f.input :total_carbs, input_html: { class: 'form-input form-control total-carbs-field' }, as: :string, as: :hidden %>
  <%= f.input :dietary_fiber, input_html: { class: 'form-input form-control dietary-fiber-field' }, as: :string, as: :hidden %>
  <%= f.input :sugars, input_html: { class: 'form-input form-control sugars-field' }, as: :string, as: :hidden %>
  <%= f.input :protein, input_html: { class: 'form-input form-control protein-field' }, as: :string, as: :hidden %>
  <%= f.input :vitamin_a, input_html: { class: 'form-input form-control vitamin-a-field' }, as: :string, as: :hidden %>
  <%= f.input :vitamin_c, input_html: { class: 'form-input form-control vitamin-c-field' }, as: :string, as: :hidden %>
  <%= f.input :calcium, input_html: { class: 'form-input form-control calcium-field' }, as: :string, as: :hidden %>
  <%= f.input :iron, input_html: { class: 'form-input form-control iron-field' }, as: :string, as: :hidden %>
  <%= f.input :nutritionix_id, input_html: { class: 'form-input form-control ingredient-id-field' }, as: :string, as: :hidden %>
  <%= f.input :serving_weight, input_html: { class: 'form-input form-control serving-weight-field' }, as: :string, as: :hidden %>
  <div class="col-xs-3">
    <%= f.submit "Add", class: "btn btn-primary"  %>
  </div>
</div>
<% end %>

app/views/ingredients/_ingredient_form.html.erb
<%= simple_form_for [@recipe, @ingredient], remote: true, html: {class: "form-inline form-horizontal"} do |f| %>
<div class="">
    <div class="col-xs-2">
      <%= f.input :qty, label: false, placeholder: "qty", input_html: { class: 'form-input form-control qty-input', :style=> 'width: 55px; padding: 3px; text-align: center'} %>
    </div>
    <div class="col-xs-2">
      <%= f.input :unit, label: false, placeholder: "g", input_html: { class: 'form-input form-control unit-input', :style=> 'width: 30px; padding: 5px; text-align: center' } %>
    </div>
    <div class="col-xs-5">
      <%= f.input :name, label: false, placeholder: "Search Ingredients", input_html: { class: 'form-input form-control search-term search-items', id: 'search-items', :style=> 'width: 190px; padding: 5px'  } %>
    </div>


  <%= f.input :calories, input_html: { class: 'form-input form-control calories-field' }, as: :string %>
  <%= f.input :total_fat, input_html: { class: 'form-input form-control total-fat-field' }, as: :string %>
  <%= f.input :saturated_fat, input_html: { class: 'form-input form-control saturated-fat-field' }, as: :string, as: :hidden %>
  <%= f.input :trans_fat, input_html: { class: 'form-input form-control trans-fat-field' }, as: :string, as: :hidden %>
  <%= f.input :cholesterol, input_html: { class: 'form-input form-control cholesterol-field' }, as: :string, as: :hidden %>
  <%= f.input :sodium, input_html: { class: 'form-input form-control sodium-field' }, as: :string, as: :hidden %>
  <%= f.input :total_carbs, input_html: { class: 'form-input form-control total-carbs-field' }, as: :string, as: :hidden %>
  <%= f.input :dietary_fiber, input_html: { class: 'form-input form-control dietary-fiber-field' }, as: :string, as: :hidden %>
  <%= f.input :sugars, input_html: { class: 'form-input form-control sugars-field' }, as: :string, as: :hidden %>
  <%= f.input :protein, input_html: { class: 'form-input form-control protein-field' }, as: :string, as: :hidden %>
  <%= f.input :vitamin_a, input_html: { class: 'form-input form-control vitamin-a-field' }, as: :string, as: :hidden %>
  <%= f.input :vitamin_c, input_html: { class: 'form-input form-control vitamin-c-field' }, as: :string, as: :hidden %>
  <%= f.input :calcium, input_html: { class: 'form-input form-control calcium-field' }, as: :string, as: :hidden %>
  <%= f.input :iron, input_html: { class: 'form-input form-control iron-field' }, as: :string, as: :hidden %>
  <%= f.input :nutritionix_id, input_html: { class: 'form-input form-control ingredient-id-field' }, as: :string, as: :hidden %>
  <%= f.input :serving_weight, input_html: { class: 'form-input form-control serving-weight-field' }, as: :string %>
  <div class="col-xs-3">
    <%= f.submit "Add", class: "btn btn-primary"  %>
  </div>
</div>
<% end %>

app/views/ingredients/_ingredients.html.erb
<tr id="<%= dom_id(ingredient) %>">
  <td><p><%= ingredient.qty %></p></td>
  <td><p><%= ingredient.unit %></p></td>
  <td><p><%= ingredient.name %></p></td>
  <!-- <td><%#= link_to '<i class="fa fa-pencil x4"></i>'.html_safe, edit_recipe_ingredient_path(@recipe, i) %></td> -->
  <% if can? :destroy, @recipe %>
    <td><%= link_to '<i class="fa fa-trash x3"></i>'.html_safe, recipe_ingredient_path(@recipe, ingredient), method: :delete, remote: true %></td>
  <% end %>
<tr>

app/views/ingredients/create.js.erb
<% if @ingredient.errors.any? %>
  $(".ingredient-form").html("<%= j render "ingredients/ingredient_fields" %>");
<% else %>
  $(".each-ingredient").append("<%= j render partial: "ingredients/ingredients", locals: {ingredient: @ingredient} %>");
  $('#ingredient_qty').val("");
  $('#ingredient_unit').val("");
  $('#search-items').val("");
  $('.nut-table').fadeOut(300, function(){
    $('.nut-table').html("<%= j render 'recipes/nutritional_table' %>");
    updateBaseNutritionValues();
    $('.nut-table').fadeIn(300);
  });
  $('.nut-recommendation').html("<%= j render 'recipes/nutrition_recommendation' %>");

<% end %>

app/views/ingredients/create_temp.js.erb
<% if @ingredient.errors.any? %>
  $(".ingredient_form").html("<%= j render "ingredients/ingredient_fields" %>");
<% else %>
  $(".ingredients").prepend("<%= j render partial: "/ingredients/ingredient", locals: {i: @ingredient} %>");
  $("#ingredient_body").val("");
  <%# this needs to be done because @answer is persisted in this scenario %>
  <%# which means the form will be "update" instead of "create" %>
  <% @ingredient = Ingredient.new %>
  $(".ingredient_form").html("<%= j render "ingredients/ingredient_fields" %>");

<% end %>

app/views/ingredients/destroy.js.erb
$("#<%= dom_id(@ingredient) %>").fadeOut();
$('.nut-table').fadeOut(300, function(){
  $('.nut-table').html("<%= j render 'recipes/nutritional_table' %>");
  updateBaseNutritionValues();
  $('.nut-table').fadeIn(300);
});
$('.nut-recommendation').html("<%= j render 'recipes/nutrition_recommendation' %>");

app/views/ingredients/search.html.erb
<h2>All Results</h2>
<table>
<% @foods.each do |i| %>
  <tr>
  <td><%= i.long_description %></td>
      <% i.weights do |w| %>
        <%= w.gram_weight %>
        <%= w.amount %>
        <%= w.measurement_description %>
      <% end %>
    <td>Nutrient Number</td>
    <td>Nutrient Value</td>
    <td>Units</td>
  </tr>
  <tr>
  <% i.foods_nutrients.each do |n| %>
    <td></td>
    <td><%= n.nutrient_number %></td>
    <td><%= n.nutrient.nutrient_description %></td>
    <td><%= n.nutrient_value %></td>
    <td><%= n.nutrient.units %></td>
  </tr>
    <% end %>
  <% end %>
</table>