config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  root 'welcome#index'

  resources :recipes do
    resources :ingredients
    resources :directions
  end

  resources :users, only: [:new, :create]

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  layout "external"

  def index
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<div class="welcome">

  <!-- <div style="width: 100%; height: 100vh; position: fixed;" data-vide-bg="<%= asset_path('video/NutritionApp_edit.mp4') %>" data-vide-options="loop: true, muted: true, position: 0% 0%, posterType: 'detect' " class="welcome-video"> -->
  <div style="width: 100%; height: 100vh; position: fixed;" data-vide-bg="https://s3-us-west-2.amazonaws.com/nutrilabel/videos/NutritionApp_edit.mp4" data-vide-options="loop: true, muted: true, position: 0% 0%, posterType: 'detect' " class="welcome-video">


    <nav class="navbar navbar-default navbar-inverse navbar-fixed-top transparent">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <div class="navbar-header">
            <%= link_to "Nutrilabel", root_path, class: "navbar-brand" %>
          </div>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li> <a class="name">Welcome <%= current_user.full_name %></a></li>
              <li><%= link_to "Sign Out", sessions_path, method: :delete, class: "signout" %></li>
            <% else %>
              <li> <a type="button" class="sign-up-btn" data-toggle="modal" data-target="#signupModal">
              Restaurant Sign Up</a></li>
              <li> <a type="button" class="sign-in-btn" data-toggle="modal" data-target="#signinModal">Sign In</a></li>
            <% end %>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

    <div class="flash-alert">
      <% if flash[:notice] %>
        <div class="alert alert-success transparent"><%= flash[:notice] %></div>
      <% elsif flash[:alert] %>
        <div class="alert alert-danger"><%= flash[:alert] %></div>
      <% end %>
    </div>

    <div class="container welcome-message">
      <div class="col-xs-6 col-xs-offset-3">
        <h2>Welcome to Nutrilabel</h2>
        <div class="welcome-note">
          <h3>Keep your customers informed</h3>
          <h3>Generate nutritional information for your recipes</h3>
        </div>
        <div class="container col-xs-offset-2">
        <%= link_to "View Menu", recipes_path, class: "clr-btn" %>
        <%#= link_to "Demo", new_recipe_path, class: "clr-btn" %>
        <a type="button" class="clr-btn" data-toggle="modal" data-target="#signupModal">Sign Up</a>
        </div>
      </div>
    </div>
  </div>

  <div class="modal fade" id="signupModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h3 class="modal-title" id="myModalLabel">Sign Up</h3>
        </div>
          <%= render '/users/signup' %>
      </div>
    </div>
  </div>

  <div class="modal fade" id="signinModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h3 class="modal-title" id="myModalLabel">Sign In</h3>
        </div>
          <%= render '/sessions/new' %>
      </div>
    </div>
  </div>

</div>