config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  root 'welcome#index'

  resources :recipes do
    resources :ingredients
    resources :directions
  end

  resources :users, only: [:new, :create]

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end
  
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-inverse navbar-fixed-top">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="navbar-header">
        <%= link_to "Nutrilabel", root_path, class: "navbar-brand" %>
      </div>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "All Recipes", recipes_path %></li>
        <!-- Button trigger modal -->
        <% if user_signed_in? %>
          <li> <a type="button" class="new-recipe-btn" data-toggle="modal" data-target="#myModal">
          New Recipe</a></li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "Admin", admin_root_path %></li>
          <li> <a class="name">Welcome <%= current_user.full_name %></a></li>
          <li><%= link_to "Sign Out", sessions_path, method: :delete, class: "signout" %></li>
        <% else %>
          <li><%= link_to "Sign In", new_session_path %></li>
          <li><%= link_to "Sign Up", new_user_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<% if user_signed_in? %>
  <div class="modal fade new-recipe" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="myModalLabel">Add a new recipe</h4>
        </div>
          <% @recipe = Recipe.new %>
          <%= render 'new_recipe' %>
      </div>
    </div>
  </div>
<% end %>

<!-- <nav class="navbar navbar-default navbar-fixed-bottom navbar-inverse transparent">
  <div class="container">
    ...
  </div>
</nav> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nutrition</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href='http://fonts.googleapis.com/css?family=Archivo+Black' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Droid+Sans' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="internal-pages">
  <%= render "/layouts/navbar" %>

  <div class="container">
    <% if flash[:notice] %>
      <div class="alert alert-success"><%= flash[:notice] %></div>
    <% elsif flash[:alert] %>
      <div class="alert alert-danger"><%= flash[:alert] %></div>
    <% end %>
  </div>

  <%= yield %>

</div>

</body>
</html>

app/views/layouts/external.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nutrition</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href='http://fonts.googleapis.com/css?family=Archivo+Black' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>